name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 2.7 required for node-gyp
        run: |
          sudo apt-get install python2
          sudo ln -s /usr/bin/python2 /usr/bin/python
      - run: apt-get install libxtst-dev
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
